# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            StatapMY
tagline:          'StatapMY'
description:      'A directory for inspiring startup companies. <br> Made in Malaysia.'
curate:           'Curated by <a href="http://twitter.com/nurfaizfoat" target="_blank">@nurfaizfoat</a>'
url:              http://nurfaizfoat.github.io/statapMY
baseurl:          http://nurfaizfoat.github.io/statapMY

author:
  name:           'Nurfaiz Foat'
  url:            https://nrfz.org

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/nurfaizfoat/statapMY
