# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            StatapMY
tagline:          'StatapMY'
description:      'A directory for inspiring startup companies. <br> Made in Malaysia.'
curate:           'Curated by <a href="http://twitter.com/nurfaizfoat" target="_blank">@nurfaizfoat</a>'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
